mongodb/mongo-efcore-provider

- src/MongoDB.EntityFrameworkCore/Storage/MongoDatabaseWrapper.cs
Share Identity changes are when an identity with a given ID/PK is deleted and another is added without an intermediate savechanges between them.
In the case of root level elements existing EF Core providers (Cosmos, relational) treat this as an update right now however we can not do so as we issue partial updates to MongoDB that would result in expected merges of data.
EF Core also plans to stop doing this in the future for their providers https://github.com/dotnet/efcore/issues/30705
Once we've completed #21 we should test and fix (if necessary) the delete/add scenarios for:
- Top level/root documents (delete + add in correct order)
- Embedded/owned entities (mark parent entity as changed and ensure correct entity is serialized)
- Collections of owned entities (mark parent entity as …
> Treat shared identity updates as individual changes

- src/MongoDB.EntityFrameworkCore/Serializers/SerializationHelper.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoDatabaseWrapper.cs
Splits the key and non-key parts of seialization to ensure filtering is clear and prevent writing non-stored properties.
> Do not write non-stored properties, split key and non-key serialization

- src/MongoDB.EntityFrameworkCore/Extensions/MongoEntityTypeBuilderExtensions.cs
- src/MongoDB.EntityFrameworkCore/Extensions/MongoEntityTypeExtensions.cs
- src/MongoDB.EntityFrameworkCore/Extensions/MongoPropertyExtensions.cs
- src/MongoDB.EntityFrameworkCore/Extensions/MongoServiceCollectionExtensions.cs
- src/MongoDB.EntityFrameworkCore/Infrastructure/MongoModelValidator.cs
- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/PrimaryKeyDiscoveryConvention.cs
- src/MongoDB.EntityFrameworkCore/Query/Visitors/ProjectionBindingRemovingExpressionVisitorBase.cs
- src/MongoDB.EntityFrameworkCore/Storage/BsonBinding.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoDatabaseWrapper.cs
- src/MongoDB.EntityFrameworkCore/ValueGeneration/MongoValueGeneratorSelector.cs
- src/MongoDB.EntityFrameworkCore/ValueGeneration/OwnedEntityIndexValueGenerator.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/OwnedEntityTests.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/ValueGeneration/MongoValueGeneratorSelectorTests.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/ValueGeneration/OwnedEntityIndexValueGeneratorTests.cs
Implementation of owned entity collections.
The main issue here was handling the synthetic non-stored keys on the collection which as well as having the parent key like non-collections also needed another value. We use a generator even though we don't persist or read these values to keep EF happy.
> EF-24: Owned entity collections

- src/MongoDB.EntityFrameworkCore/Query/Visitors/MongoEFToLinqTranslatingExpressionVisitor.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/OwnedEntityTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Utilities/ExtensionMethods.cs
Allows an entity containing two or more properties with owned entities to be materialized and stored.
> EF-58 fix multiple owned entities

- src/MongoDB.EntityFrameworkCore/Extensions/MongoServiceCollectionExtensions.cs
- src/MongoDB.EntityFrameworkCore/Query/Factories/MongoQueryTranslationPostprocessorFactory.cs
- src/MongoDB.EntityFrameworkCore/Query/Factories/MongoQueryTranslationPreprocessorFactory.cs
- src/MongoDB.EntityFrameworkCore/Query/MongoQueryTranslationPreprocessor.cs
- src/MongoDB.EntityFrameworkCore/Query/QueryingEnumerable.cs
- src/MongoDB.EntityFrameworkCore/Query/Visitors/FinalPredicateHoistingVisitor.cs
- src/MongoDB.EntityFrameworkCore/Query/Visitors/MongoQueryableMethodTranslatingExpressionVisitor.cs
- src/MongoDB.EntityFrameworkCore/Query/Visitors/MongoShapedQueryCompilingExpressionVisitor.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/TopScalarTests.cs
Fixes EF-61 in order to support some top-level operations such as Count, LongCount and Any.
Other operators like Sum, Max etc. are not able to be supported yet as we don't support projections which would be required.
Additionally All can not be supported as there is no non-predicate version available for us to use once we hoist the predicate up to a where clause.
> Support count, longcount and any at top-level.

- src/MongoDB.EntityFrameworkCore/Query/QueryingEnumerable.cs
- src/MongoDB.EntityFrameworkCore/Query/Visitors/MongoShapedQueryCompilingExpressionVisitor.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/ProjectionTests.cs
We planned to originally support a couple of projection types in preview 1 but they didn't make the cut-off and were limited to only Tuple and anonymous anyway.
Just fixing them here as a refresher before evolving how we do projections to support more scenarios.
> Fix anonymous & tuple projections

- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/CamelCaseElementNameConvention.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Metadata/Conventions/CamelCasePropertyNameConventionTests.cs
While the camel case convention provider is not switched on by default it is available and in preview-1 it only applied to properties and not relationships that are owned entities.
As both of these are now supported the name is updated to reflect it applies to all element names and not just those from properties.
> EF-74: Camel case convention for all element names

- src/MongoDB.EntityFrameworkCore/Infrastructure/MongoOptionsExtension.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/Extensions/MongoDbContextOptionsExtensionsTest.cs
The `.UseMongoDb` overload that takes a connection string does not handle the MongoDB cluster format.
This is because they are not a technically valid Uri and the code was using `UriBuilder` to check for the presence of a password to ensure it is sanitized for logging purposes.
This PR switches it from `UriBuilder` to `MongoUriBuilder` which does handle the cluster format and adds test coverage.
> Handle cluster connection strings in the UseMongoDb overload.

- src/MongoDB.EntityFrameworkCore/Storage/BsonBinding.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/OwnedEntityTests.cs
Ensure that we support loading BSON documents where a child document element is entirely missing from the BSON providing the element is nullable in the entity.
Fixes EF-101
> Handle no BSON element for nullable child docs

- src/MongoDB.EntityFrameworkCore/Storage/MongoDatabaseWrapper.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Update/ContextTests.cs
Previously the SaveChanges and SaveChangesAsync code only returned the number of existing documents updated and did not also include the number of documents added or deleted.
> Include add & delete in doc count from SaveChanges/Async.

- src/MongoDB.EntityFrameworkCore/Query/Visitors/ProjectionBindingRemovingExpressionVisitorBase.cs
- src/MongoDB.EntityFrameworkCore/Serializers/SerializationHelper.cs
- src/MongoDB.EntityFrameworkCore/Storage/BsonBinding.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/OwnedEntityTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/PrimitiveCollectionTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Serialization/BooleanSerializationTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Serialization/CollectionSerializationTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Serialization/DateAndTimeSerializationTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Serialization/DecimalSerializationTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Serialization/FloatingSerializationTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Serialization/GuidSerializationTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Serialization/IntegerSerializationTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Serialization/MongoTypeSerializationTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Serialization/StringSerializationTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Serialization/UnsignedIntegerSerializationTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Utilities/SingleEntityDbContext.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/Serializers/SerializationHelperTests.cs
How we initialize collections was inconsistent and difficult to use. This PR attempts to improve this although some scenarios are still less than ideal due to the limitations with EF8. Fixes [EF-105](https://jira.mongodb.org/browse/EF-105).
- Empty BSON array: Initialize as empty
- Null BSON element: Throw if non-nullable, set to null if nullable
- Missing element: Throw if non-nullable, set to null if nullable
- Empty BSON array: Initialize as empty
- Null BSON element: Initialize as null
- Missing BSON element: Throws InvalidOperation exception letting the user know
The inconsistency is because EF collect the nullability metadata from the nullable reference type annotations Roslyn emits only for properties and 1-1 based navigations not collections. We could consider doing this ourselves …
> Init primitive+owned entity collections when empty etc.

- THIRD-PARTY-NOTICES
- evergreen/evergreen.yml
- src/MongoDB.EntityFrameworkCore/Diagnostics/MongoEventId.cs
- src/MongoDB.EntityFrameworkCore/Diagnostics/MongoLoggerExtensions.cs
- src/MongoDB.EntityFrameworkCore/Diagnostics/MongoLoggingDefinitions.cs
- src/MongoDB.EntityFrameworkCore/Diagnostics/MongoQueryEventData.cs
- src/MongoDB.EntityFrameworkCore/Diagnostics/NonCapturingLazyInitializer.cs
- src/MongoDB.EntityFrameworkCore/MongoDB.EntityFrameworkCore.csproj
- src/MongoDB.EntityFrameworkCore/Query/MongoExecutableQuery.cs
- src/MongoDB.EntityFrameworkCore/Query/QueryingEnumerable.cs
- src/MongoDB.EntityFrameworkCore/Query/Visitors/MongoShapedQueryCompilingExpressionVisitor.cs
- src/MongoDB.EntityFrameworkCore/Storage/IMongoClientWrapper.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoClientWrapper.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Entities/Guides/GuidesDbContext.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/LoggingTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Utilities/SpyLogging.cs
Fixes EF-50.
- Fair amount of logging infra as this is our first custom log
- MQL is only logged for enumerable sets not first/single (will address in another PR)
- MQL can only be logged with the parameters in place so queries only show if sensitive logging is enabled
- Logging of other operations in future PRs
> Add support for MQL query logging

- src/MongoDB.EntityFrameworkCore/Query/Visitors/MongoShapedQueryCompilingExpressionVisitor.cs
- src/MongoDB.EntityFrameworkCore/Serializers/SerializationHelper.cs
- src/MongoDB.EntityFrameworkCore/Storage/IMongoClientWrapper.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoClientWrapper.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoDatabaseWrapper.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoUpdate.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoUpdateBatch.cs
The update code was somewhat tangled and lead to exposure of parts we didn't really want such as IMongoDatabase on the wrapper. Instead, now:
- `MongoUpdate` - contains the collection + WriteModel for each document update & doc writing code
- `MongoBatchUpdate` - groups the MongoUpdate operations into per-collection batches
- `SerializationHelper` - loses the document writing that only MongoUpdate needed
- `IMongoClientWrapper` - stops exposing the whole of IMongoDatabase, trading it for GetCollection and SaveUpdates/Async
- `MongoClientWrapper` - implements the interface changes
- `MongoDatabaseWrapper` - Delegates out functionality to MongoUpdate and the MongoBatchUpdate
This leaves the pieces with a clear, specific focus and makes it easier for the logging of bulk operations to happen …
> Clean up update pipeline prior to logging

- src/MongoDB.EntityFrameworkCore/Diagnostics/MongoBulkWriteEventData.cs
- src/MongoDB.EntityFrameworkCore/Diagnostics/MongoEventId.cs
- src/MongoDB.EntityFrameworkCore/Diagnostics/MongoLoggerExtensions.cs
- src/MongoDB.EntityFrameworkCore/Diagnostics/MongoLoggingDefinitions.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoClientWrapper.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/LoggingTests.cs
Fixes EF-110.
Provides a log message/log event for bulk write operations as we use them instead of sequential serialized individual updates.
Note that these bulk writes are batched but preserve EF-supplied ordering so you may see multiple bulk operations for the same collection name with other intermediate bulk write operations between them.
This PR also adds using type aliases for the two generic EventDefinition signatures in order to reduce noise and improve clarity.
> Implement bulk write logging

- src/MongoDB.EntityFrameworkCore/Infrastructure/MongoModelValidator.cs
- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/MongoConventionSetBuilder.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Mapping/DiscriminatorTests.cs
BsonTimeSpanOptionsAttribute was already coded but not registered.
New code to detect type discriminators and throw as they're not supported in next release.
> Prevent unsupported type discriminators & BsonTimeSpanOptionsAttribute

- src/MongoDB.EntityFrameworkCore/EnumerableMethods.cs
- src/MongoDB.EntityFrameworkCore/ExpressionExtensionMethods.cs
- src/MongoDB.EntityFrameworkCore/Query/Visitors/MongoProjectionBindingExpressionVisitor.cs
- src/MongoDB.EntityFrameworkCore/Query/Visitors/ProjectionBindingRemovingExpressionVisitorBase.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/OwnedEntityTests.cs
Previously threw an error because the parameter was not correctly remapped into a shaper and replaced.
Now supports serialization, deserialization and querying on owned entities having owned entities.
Fixes EF-83
> Handle owned entities having owned entities

- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/GlobalQueryTests.cs
Adds a few tests to ensure that EF global filters are supported.
Related to EF-112 but that ticket needs more info for a full resolution.
> Add some test coverage for global filters

- tests/MongoDB.EntityFrameworkCore.UnitTests/Extensions/MongoDbContextOptionsExtensionsTest.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/Metadata/Conventions/BsonAttributes/BsonDateTimeOptionsAttributeConventionTests.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/Metadata/Conventions/BsonAttributes/BsonElementAttributeConventionTests.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/Metadata/Conventions/BsonAttributes/BsonIgnoreAttributeConventionTests.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/Metadata/Conventions/BsonAttributes/BsonRequiredAttributeConventionTests.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/Metadata/Conventions/CollectionAttributeConventionTests.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/Metadata/Conventions/CollectionNameFromDbSetConventionTests.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/Metadata/Conventions/ColumnAttributeConventionTests.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/Metadata/Conventions/PrimaryKeyDiscoveryConventionTests.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/Metadata/Conventions/TableAttributeConventionTests.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/Query/Expressions/MongoCollectionExpressionTests.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/Query/Expressions/MongoQueryExpressionTests.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/TestUtilities/MongoTestHelpers.cs
Started getting some of the EF multiple service warnings as more tests were not using the SingleEntityContext helper.
> Prevent EF multiple service warnings in more tests

- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/ColumnAttributeConvention.cs
- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/PrimaryKeyDiscoveryConvention.cs
- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/TableAttributeConvention.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Metadata/Conventions/ColumnAttributeConventionTests.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/Metadata/Conventions/TableAttributeConventionTests.cs
Although we support the Table and Column attribute we don't support Table.Schema or Column.TypeName parts of them.
This PR throws if we encounter those.
We are intentionally allowing the unsupported Column.Order through as it has no data loss implications.
> Detect unsupported attribute properties

- src/MongoDB.EntityFrameworkCore/Query/MongoQueryCompilationContext.cs
- src/MongoDB.EntityFrameworkCore/Query/Visitors/MongoEFToLinqTranslatingExpressionVisitor.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/GlobalQueryTests.cs
Sometimes EF injects parameters quite late in the process.
Because we override the QueryExecutor we weren't getting these parameters added to the QueryContext we use for parameter resolution.
Fixes EF-112
> Implement runtime inserted EF parameters

- src/MongoDB.EntityFrameworkCore/Extensions/MongoServiceCollectionExtensions.cs
- src/MongoDB.EntityFrameworkCore/Serializers/ValueConverterSerializer.cs
- src/MongoDB.EntityFrameworkCore/Storage/ValueConversion/MongoValueConverterSelector.cs
- src/MongoDB.EntityFrameworkCore/Storage/ValueConversion/ObjectIdToStringConverter.cs
- src/MongoDB.EntityFrameworkCore/Storage/ValueConversion/StringObjectIdConverter.cs
- src/MongoDB.EntityFrameworkCore/Storage/ValueConversion/StringToObjectIdConverter.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Mapping/ValueConverterTests.cs
Just a few tests to make sure the default ones are detected.
Not all default converters might work - it will depend on what they do and whether the Mongo C# LINQ driver supports those expressions.
> Add default ValueConverter test coverage

- apidocs/docfx.json
- evergreen/build-apidocs.sh
- evergreen/evergreen.yml
Bumped DOCFX version to support the latest language features (primary constructors first of all)
Added API docs validation script to be runned on Main and PR build for earlier problems detection.
> Bump docfx version

- src/MongoDB.EntityFrameworkCore/Serializers/SerializationHelper.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Serialization/DateAndTimeSerializationTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Utilities/ExtensionMethods.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Utilities/TemporaryDatabaseFixture.cs
Problem was masked by precision reduction code in tests.
Fixes EF-126
> Use actual DateTimeKind specified not just local

- src/MongoDB.EntityFrameworkCore/Storage/MongoTypeMappingSource.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Mapping/ClrTypeMappingTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Update/AddEntityTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Update/UpdateEntityTests.cs
The built-in converters don't handle null internally (we have a separate issue to tackle that for non-enum value converters)
This changes Enum handling to go back to our built-in conversion which will also retain better compatibility with the C# driver.
Fixes EF-128
> Use Mongo C# Driver for enum mapping over built-in EF converters

- src/MongoDB.EntityFrameworkCore/Extensions/MongoPropertyBuilderExtensions.cs
- src/MongoDB.EntityFrameworkCore/Extensions/MongoPropertyExtensions.cs
- src/MongoDB.EntityFrameworkCore/Metadata/MongoAnnotationNames.cs
- src/MongoDB.EntityFrameworkCore/Serializers/SerializationHelper.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Exerciser.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Mapping/BsonTypeTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Serialization/DateAndTimeSerializationTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Update/AddEntityTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Update/UpdateEntityTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Utilities/ExtensionMethods.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/Extensions/MongoPropertyBuilderExtensionsTests.cs
Provides a `HasBsonType` fluent API that allows the model builder to configure specific properties to be stored as specific BSON types.
Fixes EF-127
A subsequent PR will further expose this feature out so that `BsonRepresentation` attributes can be recognized (EF-44)
> BsonType configuration 

- src/MongoDB.EntityFrameworkCore/Query/QueryingEnumerable.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoClientWrapper.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/LoggingTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Utilities/TestServer.cs
Previously if the LINQ provider threw the MQL would not be logged.
This change ensures we always log the MQL even if it does throw as it is very useful in debugging certain throwing scenarios.
Small test cleanup in the touched LoggingTests to reduce boilerplate in finding the correct log entry.
Fixes EF-142
> EF-142: Log MQL even when LINQ driver throws.

- src/MongoDB.EntityFrameworkCore/Serializers/EntitySerializer.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/OwnedEntityTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/WhereTests.cs
Previously we did not support matching entire owned entities for where/contains/first etc. 
This adds support for that by ensuring the entity serializer can serialize the EF entity back to the Bson document for matching.
Fixes EF-131.
> EF-131: Support matching on owned entity values

- sbom.json
Empty SBOM since EF doesn't have any third party dependencies matching the SSDLC spec criteria.
> EF-140: Third Party Dependencies Report for Entity Framework

- src/MongoDB.EntityFrameworkCore/Diagnostics/MongoLoggerExtensions.cs
- src/MongoDB.EntityFrameworkCore/MongoDB.EntityFrameworkCore.csproj
- src/MongoDB.EntityFrameworkCore/Query/MongoExecutableQuery.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoClientWrapper.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Mapping/ValueConverterTests.cs
As well as updating the NuGet reference there are two small changes that directly relate to 2.26.0:
1. The unit test that previously failed because of a bug in the C# Driver is now re-enabled
2. The logging code no longer needs to use reflection and is cleaned up to reflect the simpler pattern
> Upgrade to C# Driver 2.26.0

- MongoDB.EFCoreProvider.sln.DotSettings
- src/MongoDB.EntityFrameworkCore/Diagnostics/NonCapturingLazyInitializer.cs
- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/BsonAttributes/BsonRepresentationAttributeConvention.cs
- src/MongoDB.EntityFrameworkCore/Query/Expressions/EntityProjectionExpression.cs
- src/MongoDB.EntityFrameworkCore/Query/Expressions/ProjectionExpression.cs
- src/MongoDB.EntityFrameworkCore/Query/Visitors/MongoEFToLinqTranslatingExpressionVisitor.cs
- src/MongoDB.EntityFrameworkCore/Serializers/SerializationHelper.cs
- src/MongoDB.EntityFrameworkCore/Serializers/ValueConverterSerializer.cs
- tests/Directory.Build.props
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Mapping/ClrTypeMappingTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/MongoDB.EntityFrameworkCore.FunctionalTests.csproj
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/OwnedEntityTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/PrimitiveCollectionTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/WhereTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Serialization/DateAndTimeSerializationTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Serialization/DecimalSerializationTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Update/AddEntityTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Update/OwnedNavigationPropertyCrudTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Update/UpdateEntityTests.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/Metadata/Attributes/CollectionAttributeTests.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/MongoDB.EntityFrameworkCore.UnitTests.csproj
Mostly just around null annotations but also a few unused properties etc.
Solution now compiles 100% clean with Roslyn, no warnings.
> Address compiler warnings

- src/MongoDB.EntityFrameworkCore/ChangeTracking/NullableStringDictionaryComparer.cs
- src/MongoDB.EntityFrameworkCore/ChangeTracking/StringDictionaryComparer.cs
- src/MongoDB.EntityFrameworkCore/Serializers/CollectionSerializationProvider.cs
- src/MongoDB.EntityFrameworkCore/Serializers/DictionarySerializationProvider.cs
- src/MongoDB.EntityFrameworkCore/Serializers/SerializationHelper.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoTypeMappingSource.cs
- src/MongoDB.EntityFrameworkCore/TypeExtensionMethods.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/WhereDictionaryTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Serialization/CollectionSerializationTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Serialization/DictionarySerializationTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Update/UpdateEntityTests.cs
Implements EF-47 for Dictionary/ReadOnlyDictionary support.
Note: One test is disabled as there is a bug in the C# Driver that prevents this indexers being used on IReadOnlyDictionary. Being tracked as CSHARP-5171,
> EF-47: Dictionary & ReadOnlyDictionary property support

- src/MongoDB.EntityFrameworkCore/MongoDB.EntityFrameworkCore.csproj
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/ProjectionTests.cs
Had to remove an array test as 2.28.0 doesn't support mixed-value arrays any more - CSHARP-4957
> Upgrade EF to 8.0.7 and MongoDB.Driver to 2.28.0

- evergreen/evergreen.yml
Required to ensure transactional tests work correctly.
Considered trying to create a subset of transactional to be able to continue to perform majority of tests on standalone but the default is transactions on and we'd still have to cover a fair set of combinations.
> Switch evergreen to replicasets for transaction support.

- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Design/Generated/EveryTypeEntityType.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Design/Generated/SimpleContextModelBuilder.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/WhereDictionaryTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/WhereTests.cs
Just removes the skip from two tests which are now fine to run as well as a two regenerated test files.
> Enable tests fixed by updates to EF/Driver

- src/MongoDB.EntityFrameworkCore/Query/MongoQueryCompilationContext.cs
- src/MongoDB.EntityFrameworkCore/Serializers/SerializationHelper.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Mapping/ClrTypeMappingTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Update/DeleteEntityTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Utilities/TemporaryDatabaseFixture.cs
Originally considered exposing an API to allow and specify how the Guid was stored but with the move to V3/Standard and the other formats effectively being deprecated it makes sense just to change the defaults.
This will be a breaking change and will need to be called out in the release notes.
> EF-154: Switch Guid binary format over to V3/Standard

- src/MongoDB.EntityFrameworkCore/Storage/IMongoClientWrapper.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoClientWrapper.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoDatabaseCreator.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Serialization/DictionarySerializationTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Storage/MongoClientWrapperTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Storage/MongoDatabaseCreatorTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Utilities/TemporaryDatabaseFixture.cs
CreateDatabase(Async) was previously a no-op as we allowed the database and collections to create on-demand.
Now that transactions are enabled by default there are some situations where creating a collection or database inside the transaction can cause issues.
Instead now we will create any missing empty collections from inside CreateDatabase to avoid these situations as it should be called at app start-up outside of any transaction.
> EF-155: Create empty collections when inside CreateDatabase

- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Update/SaveChangesTransactionTests.cs
Just an extra couple of tests to ensure auto transactions roll back all collections affected not just one.
> Add multi-collection transaction tests

- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/CamelCaseElementNameConvention.cs
- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/CollectionNameFromDbSetConvention.cs
- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/ColumnAttributeConvention.cs
- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/MongoRelationshipDiscoveryConvention.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Metadata/Conventions/CamelCaseElementNameConventionTests.cs
Minor clean-up to some conventions for performance and ease of use.
Aware of small breaks, will add to the docs for 8.1.0
> Clean up some conventions

- src/MongoDB.EntityFrameworkCore/Extensions/MongoServiceCollectionExtensions.cs
- src/MongoDB.EntityFrameworkCore/Infrastructure/MongoModelRuntimeInitializer.cs
- src/MongoDB.EntityFrameworkCore/Query/MongoQueryCompilationContext.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Utilities/TemporaryDatabaseFixture.cs
Previously the V3 Guid mode was set when a query was run. This means if data was inserted before any queries it used the V2 non-standard mode resulting in exception messages.
This moves the configuration of the BsonDefaults static to DbContext initialization.
> EF-163: Set V3 Guid mode at initialization

- MongoDB.EFCoreProvider.sln
- nuget.config
- src/MongoDB.EntityFrameworkCore/Infrastructure/MongoModelRuntimeInitializer.cs
- src/MongoDB.EntityFrameworkCore/MongoDB.EntityFrameworkCore.csproj
- src/MongoDB.EntityFrameworkCore/Query/Visitors/MongoEFToLinqTranslatingExpressionVisitor.cs
- src/MongoDB.EntityFrameworkCore/Query/Visitors/MongoShapedQueryCompilingExpressionVisitor.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoClientWrapper.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/MongoDB.EntityFrameworkCore.FunctionalTests.csproj
- tests/MongoDB.EntityFrameworkCore.UnitTests/MongoDB.EntityFrameworkCore.UnitTests.csproj
Give us a project configuration "Debug 3.0 Driver" which allows using the MongoDB C# Driver 3.0 pre-release.
This will help us continue developing and provide an easy migration when we switch to the 3.0 driver after it is released.
> Add project config to allow 2.28 or 3.0 driver

- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Mapping/ValueConverterTests.cs
Latest changes to C# Driver store Decimals as Decimal128.
This exposed a miconfigured test that was supposed to store Decimals as Strings explicitly but was in fact doing it implicitly due to the default value converter configuring the wrong entity.
> Fix test that was broken on latest C# Driver branch

- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/BsonAttributes/BsonTimeSpanOptionsAttributeConvention.cs
- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/MongoConventionSetBuilder.cs
Small silly typo crept in at some point in the past.
Technically this is a breaking change as it's public but I'd be surprised if anyone used it. Should still mention it in the 8.2 release notes/breaking changes though just to be sure.
> Noticed a typo in the BsonTimeSpanOptionsAttributeConvention.cs

- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Compatibility/StoredDataStillReadableTests.cs
Many serialization settings changed in the 3.0 release of the MongoDB C# Driver that this EF Provider relies upon.
These tests include BSON documents serialized with the 2.x release (8.1 of the MongoDB EF Provider) that are then used to populate a database, attempted to be read with the 3.x driver and compared to ensure upgrades are smooth or at least detected and documented.
> New functional tests to ensure data compatibility

- src/MongoDB.EntityFrameworkCore/Infrastructure/MongoModelValidator.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoUpdate.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Mapping/DiscriminatorTests.cs
Enables type discriminators to be used without a mapped property by relaxing some of the shadow property validation and ensuring type discriminator shadow properties are always serialized.
> EF-171: Allow type discriminators without mapped property

- src/MongoDB.EntityFrameworkCore/Extensions/MongoIndexBuilderExtensions.cs
- src/MongoDB.EntityFrameworkCore/Extensions/MongoIndexExtensions.cs
- src/MongoDB.EntityFrameworkCore/Metadata/MongoAnnotationNames.cs
- src/MongoDB.EntityFrameworkCore/Storage/IMongoClientWrapper.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoClientWrapper.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoDatabaseCreator.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Storage/MongoClientWrapperTests.cs
```csharp
mb.Entity<Address>().HasIndex(a => new { a.Country, a.PostCode }, "country_zip");
mb.Entity<Company>().HasIndex(c => c.OrderRef).IsUnique();
mb.Entity<Orders>().HasIndex(o => o.OrderDate).IsDescending();
mb.Entity<Documents>()
.HasIndex(d => d.DocRef)
.HasCreateIndexOptions(new CreateIndexOptions { Sparse = true });
```
- Single property, multi-property and string named property specification
- Explicit name and generated name indexes
- Descending and mixed ordering
- Unique indexes
- Sparse & custom options through HasCreateIndexOptions
- MQL-based partialFilter support through CreateIndexOptions<BsonDocument>
This is not a migration system. Developers will need to write manual code that uses the MongoDB C# Driver if they need to delete or modify existing indexes. 
As per the …
> EF-173: Support HasIndex by creating them during CreateDatabase

- evergreen/evergreen.yml
- evergreen/sign-packages.sh
This commit templates our authenticode key name in preparation for the authenticode 2021 deprecation. The variable will be added to our Evergreen project as mongo-authenticode-2024.
> DEVPROD-13322: template authenticode key name

- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/MongoValueGenerationConvention.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/Metadata/Conventions/MongoValueGenerationConventionTests.cs
By default Entity Framework annotates key properties of specific types as ValueGenerated.OnAdd despite there being no EF-provided value generators to go with them by default.
In EF8 this was not a problem as people could still specify them manually but in EF9 this throws an exception if there is no generator available even though it already has a value. 
This PR changes our MongoValueGenerationConvention to no longer defer to the built-in ValueGenerationConvention for anything except Guid.
Fixes EF-182 and related to https://github.com/dotnet/efcore/issues/35422
> EF-182: Stop EF from defaulting key properties as ValueGenerated.OnAdd

- src/MongoDB.EntityFrameworkCore/Extensions/MongoPropertiesConfigurationBuilderExtensions.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/Extensions/MongoPropertiesConfigurationBuilderExtensionsTests.cs
> Not sure whether this fits the category of allowed contributions. If there are adjustments required, I can make them.
This allows configuration of properties of a certain type to have one particular representation in the whole context as compared to having this done from one property to another.
Example:
```cs
private class Customer
{
public int Id { get; set; }
public DateTimeOffset CreatedAt { get; set; }
public DateTimeOffset UpdatedAt { get; set; }
public DateTimeOffset? ArchivedAt { get; set; }
}
private class OrdersDbContext : DbContext
{
public DbSet<Customer> Customers { get; set; }
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
=> optionsBuilder.UseMongoDB("mongodb://localhost:27017", "mydB");
protected override void …
```
> EF-195: Support setting BSON representation on PropertiesConfigurationBuilder

- src/MongoDB.EntityFrameworkCore/Query/MongoQueryTranslationPreprocessor.cs
- src/MongoDB.EntityFrameworkCore/Query/Visitors/EntityFrameworkDetourExpressionVisitor.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/OwnedEntityTests.cs
https://jira.mongodb.org/browse/EF-199
The (temporary) solution here until EF allows us to opt-out of this behavior is to wrap the property access in a cast which is sufficient enough to break the pattern matching in EF Core's NavigationExpandingExpressionVisitor.
> EF-199: Allow navigation collections to be tested for nullability

- evergreen/evergreen.yml
This is required to make some of the tests MongoDB version-specific such as those in #197
> Update Evergreen CI test to add MONGODB_VERSION

- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/PrimaryKeyDiscoveryConvention.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoClientWrapper.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Mapping/ValueConverterTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Storage/MongoClientWrapperTests.cs
- Adds support for [EF Alternate Keys](https://jira.mongodb.org/browse/EF-207) backed with MongoDB unique indexes
- Also fixes a [rogue exception](https://jira.mongodb.org/browse/EF-206) when EF temporarily adds multiple keys during model construciton
> EF-207: Add support for Entity Framework alternate keys

- src/MongoDB.EntityFrameworkCore/Diagnostics/MongoEventId.cs
- src/MongoDB.EntityFrameworkCore/Diagnostics/MongoLoggerExtensions.cs
- src/MongoDB.EntityFrameworkCore/Diagnostics/MongoLoggingDefinitions.cs
- src/MongoDB.EntityFrameworkCore/Extensions/MongoDbContextOptionsExtensions.cs
- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/ColumnAttributeConvention.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Metadata/Conventions/ColumnAttributeConventionTests.cs
Currently, the provider throws when a ColumnAttribute is encountered. This can be helpful for people who think it will be used, when it isn't. However, there are cases where already existing entity types must be used, and in these cases the column attributes can be ignored. We can allow this by making this message into an exception by default, but changeable to a log or ignore, using EF's infrastructure.
> EF-212: Allow exception suppression when entity type property has ColumnAttribute

- src/MongoDB.EntityFrameworkCore/Extensions/MongoDbContextOptionsExtensions.cs
- src/MongoDB.EntityFrameworkCore/Extensions/MongoEntityTypeBuilderExtensions.cs
- src/MongoDB.EntityFrameworkCore/Extensions/MongoEntityTypeExtensions.cs
- src/MongoDB.EntityFrameworkCore/Extensions/MongoIndexBuilderExtensions.cs
- src/MongoDB.EntityFrameworkCore/Extensions/MongoPropertyBuilderExtensions.cs
- src/MongoDB.EntityFrameworkCore/Extensions/MongoPropertyExtensions.cs
- tests/MongoDB.EntityFrameworkCore.SpecificationTests/MongoApiConsistencyTest.cs
- -- Non-generic fluent returns that aren't hidden --
- PropertyBuilder MongoPropertyBuilderExtensions.HasDateTimeKind(PropertyBuilder, DateTimeKind)
- AV: Added
- DbContextOptionsBuilder MongoDbContextOptionsExtensions.UseMongoDB(DbContextOptionsBuilder, MongoOptionsExtension, Action`1)
- AV: Added
- -- Errors: --
- MongoPropertyBuilderExtensions expected to have a CanSetDateTimeKind or CanHaveDateTimeKind method
- Added
- MongoIndexBuilderExtensions.CanSetCreateIndexOptions(IConventionIndexBuilder, CreateIndexOptions, Boolean) expected to have the first parameter of type CreateIndexOptions<BsonDocument>
- Removed the generic overload--minor binary break, but not a source break.
- -- Errors: --
- MongoPropertyExtensions.SetBsonRepresentation(IConventionProperty, Nullable`1, Nullable`1, …
> EF-258: API consistency checks and related fixes

- evergreen/evergreen.yml
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Encryption/EncryptionTests.cs
- Adds MongoDB v8 as a named axis
- Skips the tests that break on latest/win due to upstream bug
> Change testing/matrix
