mongodb/mongo-efcore-provider

- src/MongoDB.EntityFrameworkCore/Infrastructure/MongoModelValidator.cs
- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/MongoConventionSetBuilder.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/TestUtilities/MongoTestHelpers.cs
A couple of tweaks and small fixes to pull out of the owned entity collection work to make that PR smaller.
> Small clean-up pieces

- .editorconfig
- evergreen/evergreen.yml
- evergreen/install-dependencies.sh
- evergreen/run-tests.sh
- evergreen/set-github-auth.sh
- tests/Directory.Build.props
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Infrastructure/MongoModelValidatorTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Mapping/ClrTypeMappingTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Update/AddEntityTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Update/UpdateEntityTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Utilities/TemporaryDatabaseFixture.cs
Please note except of CI script itself there are some changes related to the MongoDB 4.2 collection name limit. Some tests were updated to use shorter collection name.
> Evergreen CI script

- src/MongoDB.EntityFrameworkCore/ExceptionHelpers.cs
- src/MongoDB.EntityFrameworkCore/Extensions/MongoDbContextOptionsExtensions.cs
- src/MongoDB.EntityFrameworkCore/Infrastructure/MongoOptionsExtension.cs
- src/MongoDB.EntityFrameworkCore/MongoDB.EntityFrameworkCore.csproj
- src/MongoDB.EntityFrameworkCore/NamingHelperMethods.cs
It's low-effort to support .NET 6, it is what EF Core 7 supports and it is an LTS so worth supporting I think.
> Support .NET 6

- src/MongoDB.EntityFrameworkCore/MongoDB.EntityFrameworkCore.csproj
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/MongoDB.EntityFrameworkCore.FunctionalTests.csproj
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Update/CompositeKeyCrudTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Update/OwnedNavigationPropertyCrudTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Update/SimpleKeyCrudTests.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/MongoDB.EntityFrameworkCore.UnitTests.csproj
Upgrades some dependencies and addresses a change in XUnit behavior that caused problems with BsonDocument comparisons.
> Upgrade EF, XUnit, Test.SDK etc. to latest compatible versions

- evergreen/evergreen.yml
- evergreen/install-dependencies.sh
- global.json
- src/MongoDB.EntityFrameworkCore/MongoDB.EntityFrameworkCore.csproj
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/MongoDB.EntityFrameworkCore.FunctionalTests.csproj
- tests/MongoDB.EntityFrameworkCore.UnitTests/MongoDB.EntityFrameworkCore.UnitTests.csproj
Upgrades the projects to .NET 8.0 while still targetting EF Core 7.
Fixes [#EF-98](https://jira.mongodb.org/browse/EF-94)
> Upgrade to .NET 8

- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/MongoConventionSetBuilder.cs
- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/MongoValueGenerationConvention.cs
- src/MongoDB.EntityFrameworkCore/TypeExtensionMethods.cs
- src/MongoDB.EntityFrameworkCore/ValueGeneration/MongoValueGeneratorSelector.cs
- src/MongoDB.EntityFrameworkCore/ValueGeneration/ObjectIdValueGenerator.cs
- src/MongoDB.EntityFrameworkCore/ValueGeneration/OwnedEntityIndexValueGenerator.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Update/AddEntityTests.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/ValueGeneration/MongoValueGeneratorSelectorTests.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/ValueGeneration/ObjectIdValueGeneratorTests.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/ValueGeneration/OwnedEntityIndexValueGeneratorTests.cs
Fixes #92
This PR includes some clean up and refactoring which has been separated out into individual commits for easy review.
> Support for auto-generated ObjectId

- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/BsonAttributes/BsonElementAttributeConvention.cs
- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/ColumnAttributeConvention.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Metadata/Conventions/BsonAttributes/BsonElementAttributeConventionTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Metadata/Conventions/ColumnAttributeConventionTests.cs
> Support configuring owned entity properties with Column/BsonElement

- src/MongoDB.EntityFrameworkCore/MongoDB.EntityFrameworkCore.csproj
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/MongoDB.EntityFrameworkCore.FunctionalTests.csproj
- tests/MongoDB.EntityFrameworkCore.UnitTests/MongoDB.EntityFrameworkCore.UnitTests.csproj
Not upgrading the coverlet/test log deps.
> Upgrade EF, MongoDB & XUnit/Test dependencies

- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Mapping/ValueConverterTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/GlobalQueryTests.cs
Ensures Evergreen tests pass all combinations of MongoDB/OS.
> Shorten some test db names

- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/BsonAttributes/BsonDefaultValueAttributeConvention.cs
- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/BsonAttributes/BsonDictionaryOptionsAttributeConvention.cs
- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/BsonAttributes/BsonExtraElementsAttributeConvention.cs
- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/BsonAttributes/BsonGuidRepresentationAttributeConvention.cs
- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/BsonAttributes/BsonIgnoreIfDefaultAttributeConvention.cs
- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/BsonAttributes/BsonIgnoreIfNullAttributeConvention.cs
- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/BsonAttributes/BsonRepresentationAttributeConvention.cs
- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/BsonAttributes/BsonRequiredAttributeConvention.cs
- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/BsonAttributes/BsonSerializerPropertyConvention.cs
- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/BsonAttributes/BsonTimeSpanOptionsAttributeConvention.cs
Minor text and language improvement to the Bson not supported attributes.
> Clean up Bson attribute XML docs

- src/MongoDB.EntityFrameworkCore/Storage/ValueConversion/Decimal128DecimalConverter.cs
- src/MongoDB.EntityFrameworkCore/Storage/ValueConversion/Decimal128ToDecimalConverter.cs
- src/MongoDB.EntityFrameworkCore/Storage/ValueConversion/DecimalToDecimal128Converter.cs
- src/MongoDB.EntityFrameworkCore/Storage/ValueConversion/MongoValueConverterSelector.cs
- src/MongoDB.EntityFrameworkCore/Storage/ValueConversion/ObjectIdToStringConverter.cs
- src/MongoDB.EntityFrameworkCore/Storage/ValueConversion/StringObjectIdConverter.cs
- src/MongoDB.EntityFrameworkCore/Storage/ValueConversion/StringToObjectIdConverter.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Mapping/ValueConverterTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Utilities/TemporaryDatabaseFixture.cs
Add a default conversion for Decimal <> Decimal128 conversions as a precursor for the BSON Representation attribute work.
Fixes EF-125
> Add Decimal128 conversion

- src/MongoDB.EntityFrameworkCore/MongoDB.EntityFrameworkCore.csproj
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/MongoDB.EntityFrameworkCore.FunctionalTests.csproj
- tests/MongoDB.EntityFrameworkCore.UnitTests/MongoDB.EntityFrameworkCore.UnitTests.csproj
- EF from 8.0.4 to 8.0.6
- XUnit from 2.5.7 to 2.8.1
- Microsoft.Test.SDK from 17.9.0 to 17.10.0
> Upgrade dependencies

- evergreen/download-augmented-sbom.sh
- evergreen/evergreen.yml
- evergreen/template_ssdlc_compliance_report.md
Link to passing sbom download test: https://spruce.mongodb.com/version/666b32ebe21b7a0007481721/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> EF-132: Integrate with Silk and generate SBOM documents for releases

- src/MongoDB.EntityFrameworkCore/Diagnostics/MongoBulkWriteEventData.cs
- src/MongoDB.EntityFrameworkCore/Diagnostics/MongoDbContextEventData.cs
- src/MongoDB.EntityFrameworkCore/Diagnostics/MongoEventId.cs
- src/MongoDB.EntityFrameworkCore/Diagnostics/MongoLoggerExtensions.cs
- src/MongoDB.EntityFrameworkCore/Diagnostics/MongoLoggerTransactionExtensions.cs
- src/MongoDB.EntityFrameworkCore/Diagnostics/MongoLoggerUpdateExtensions.cs
- src/MongoDB.EntityFrameworkCore/Diagnostics/MongoLoggingDefinitions.cs
- src/MongoDB.EntityFrameworkCore/Diagnostics/MongoTransactionEndEventData.cs
- src/MongoDB.EntityFrameworkCore/Diagnostics/MongoTransactionErrorEventData.cs
- src/MongoDB.EntityFrameworkCore/Diagnostics/MongoTransactionEventData.cs
- src/MongoDB.EntityFrameworkCore/Diagnostics/MongoTransactionStartingEventData.cs
- src/MongoDB.EntityFrameworkCore/Storage/IMongoClientWrapper.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoClientWrapper.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoDatabaseWrapper.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoTransaction.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoUpdateBatch.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/LoggingTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Update/SaveChangesTransactionTests.cs
Implements EF-81.
This is for automatic transactions only. Explicit transactions require isolation levels and save-points which are on the backlog for consideration in a future release.
> Support auto transactions in SaveChanges(Async)

- src/MongoDB.EntityFrameworkCore/Storage/MongoDatabaseWrapper.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoTransaction.cs
Just additional check logic to ensure consistency.
> Track state of MongoTransaction and ensure consistent use.

- evergreen/run-tests.sh
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Utilities/TestServer.cs
Allow functional tests server to be specified by environment variable MONGODB_URI
> Read MONGODB_URI environment variable

- src/MongoDB.EntityFrameworkCore/Metadata/Conventions/CamelCaseElementNameConvention.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Metadata/Conventions/CamelCaseElementNameConventionTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/OwnedEntityTests.cs
>  EF-157: Case navigations based on property name not type name

- README.md
- src/Directory.Build.props
- README changes for 8.1.0
- Include BREAKING-CHANGES.md in Nuget just in case
> Update README for 8.1.0

- README.md
add a nuget package badge for better nuget package discovery
> docs: add nuget package badge

- tests/MongoDB.EntityFrameworkCore.FunctionalTests/LoggingTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/CollectionsResponseTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/CompositeKeyQueryTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/FindTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/InvalidQueryTranslationTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/OwnedEntityTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/PrimitiveCollectionTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/ProjectionTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/SkipTakeOrderingTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/WhereDictionaryTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Storage/MongoClientWrapperTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Storage/MongoDatabaseCreatorTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Storage/TransactionTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Update/SaveChangesTransactionTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Utilities/ReadOnlySampleGuidesFixture.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Utilities/TemporaryDatabaseFixture.cs
Just a bunch of clean-up of the functional tests for consistency, missing file header, removal of unncessary dispose since we switched to clean-up-at-start etc.
> Clean up some functional tests

- src/MongoDB.EntityFrameworkCore/Storage/MongoClientWrapper.cs
DatabaseExists/Async needs to determine if a database exists. It does this using ListDatabaseName/Async and using an appropriate name filter.
Unfortunately the name filter is not supported on some Atlas configurations so we now detect when it fails and fall back to getting the full list and filtering client side instead.
> EF-167: Fallback to using unfiltered ListDatabaseNames

- nuget.config
- src/MongoDB.EntityFrameworkCore/MongoDB.EntityFrameworkCore.csproj
- tests/Directory.Build.props
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Design/Generated/SimpleContextModelBuilder.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/MongoDB.EntityFrameworkCore.FunctionalTests.csproj
- tests/MongoDB.EntityFrameworkCore.UnitTests/MongoDB.EntityFrameworkCore.UnitTests.csproj
Upgrading all the dependencies for the 8.2.0 release
> Upgrade dependencies for EF, C# Driver, Xunit & MS Test SDK

- evergreen/evergreen.yml
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Compatibility/FieldLevelEncryptionTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/MongoDB.EntityFrameworkCore.FunctionalTests.csproj
Adds functional tests for CSFLE.
> Add client side encryption tests

- src/MongoDB.EntityFrameworkCore/Storage/MongoDatabaseWrapper.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoUpdate.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoUpdateBatch.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Update/ConcurrencyCheckTests.cs
https://jira.mongodb.org/browse/EF-174
> EF-174: Provide entries when throwing DbUpdateConcurrencyException

- src/MongoDB.EntityFrameworkCore/Storage/MongoClientWrapper.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Storage/MongoClientWrapperTests.cs
https://jira.mongodb.org/browse/EF-183
> EF-183: Support HasIndex on owned entities

- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Compatibility/FieldLevelEncryptionTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Mapping/DiscriminatorTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Mapping/ShadowPropertyTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/OwnedEntityTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Update/ConcurrencyCheckTests.cs
1. Fixes calls to CreateCollection by not passing null as first arg as it prevents CallerMemberName working.
2. Added some additional funcitonal tests when enquiries about support came in and I needed to confirm it worked.
> Test improvements

- src/MongoDB.EntityFrameworkCore/Serializers/BsonSerializerFactory.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Design/CompiledModelTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Design/Generated/EF8/EveryTypeEntityType.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Design/Generated/EF9/EveryTypeEntityType.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Design/Generated/EF9/SimpleContextModelBuilder.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Mapping/ClrTypeMappingTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Serialization/ByteArraySerializationTests.cs
https://jira.mongodb.org/browse/EF-186
> EF-186: Add support for byte arrays/binary

- src/MongoDB.EntityFrameworkCore/Serializers/BsonSerializerFactory.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Mapping/ValueConverterTests.cs
https://jira.mongodb.org/browse/EF-159
> EF-169: Make ValueConverters respect BsonRepresentation

- src/MongoDB.EntityFrameworkCore/Storage/BsonBinding.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/OwnedEntityTests.cs
https://jira.mongodb.org/browse/EF-188
> EF-188: Do not throw is BSON element missing for an owned collection

- src/MongoDB.EntityFrameworkCore/ValueGeneration/MongoValueGeneratorSelector.cs
- src/MongoDB.EntityFrameworkCore/ValueGeneration/StringObjectIdValueGenerator.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/ValueGeneration/ValueGenerationTests.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/ValueGeneration/StringObjectIdValueGeneratorTests.cs
https://jira.mongodb.org/browse/EF-189
> EF-189: Support ObjectId generation for string id stored as ObjectId

- src/MongoDB.EntityFrameworkCore/Serializers/BsonSerializerFactory.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Exerciser.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Mapping/BsonRepresentationTests.cs
Details at https://jira.mongodb.org/browse/EF-201
Breaking change for existing databases where it has not been honored.
> EF-201: Apply HasBsonRepresentation to nullable properties

- evergreen/evergreen.yml
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Compatibility/EncryptionTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Usings.cs
Addresses [EF-197](https://jira.mongodb.org/browse/EF-197)
> EF-198: Add queryable encryption test coverage

- src/MongoDB.EntityFrameworkCore/Storage/MongoUpdate.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/FindTests.cs
Tiny PR just to adjust an internal name after a code discussion.
> Standardise on compositeKeys naming (not compound)

- MongoDB.EFCoreProvider.sln
- Versions.props
- src/MongoDB.EntityFrameworkCore/MongoDB.EntityFrameworkCore.csproj
- src/MongoDB.EntityFrameworkCore/Storage/MongoDatabaseCreator.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Entities/Guides/GuidesDbContext.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Entities/Guides/Planet.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/MongoDB.EntityFrameworkCore.FunctionalTests.csproj
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Storage/MongoDatabaseCreatorTests.cs
- tests/MongoDB.EntityFrameworkCore.SpecificationTests/Mapping/BuiltInDataTypesMongoTest.cs
- tests/MongoDB.EntityFrameworkCore.SpecificationTests/MongoDB.EntityFrameworkCore.SpecificationTests.csproj
- tests/MongoDB.EntityFrameworkCore.SpecificationTests/Query/NorthwindQueryMongoFixture.cs
- tests/MongoDB.EntityFrameworkCore.SpecificationTests/Utilities/MongoTestStore.cs
- tests/MongoDB.EntityFrameworkCore.UnitTests/MongoDB.EntityFrameworkCore.UnitTests.csproj
Also:
- Remove JSON-based seeding
- Update to latest dependencies for driver and EF Core (and add a Versions file)
- Some minor test cleanup
> EF-226: Seed the database with model data on EnsureCreated

- src/MongoDB.EntityFrameworkCore/Query/Visitors/ProjectionBindingRemovingExpressionVisitor.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Mapping/ClrTypeMappingTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/OwnedEntityTests.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Update/SimpleKeyCrudTests.cs
Fixes [EF-259](https://jira.mongodb.org/browse/EF-259)
> EF-259: Support materialization of read-only properties

- src/MongoDB.EntityFrameworkCore/Query/Visitors/MongoProjectionBindingExpressionVisitor.cs
- src/MongoDB.EntityFrameworkCore/Query/Visitors/MongoProjectionBindingRemovingExpressionVisitor.cs
- src/MongoDB.EntityFrameworkCore/Query/Visitors/MongoShapedQueryCompilingExpressionVisitor.cs
- src/MongoDB.EntityFrameworkCore/Serializers/BsonSerializerFactory.cs
- src/MongoDB.EntityFrameworkCore/Serializers/EntitySerializer.cs
- src/MongoDB.EntityFrameworkCore/Storage/BsonBinding.cs
- src/MongoDB.EntityFrameworkCore/Storage/MongoUpdate.cs
- tests/MongoDB.EntityFrameworkCore.FunctionalTests/Query/ProjectionTests.cs
- tests/MongoDB.EntityFrameworkCore.SpecificationTests/Query/NorthwindGroupByQueryMongoTest.cs
- tests/MongoDB.EntityFrameworkCore.SpecificationTests/Query/NorthwindMiscellaneousQueryMongoTest.cs
- tests/MongoDB.EntityFrameworkCore.SpecificationTests/Query/NorthwindNavigationsQueryMongoTest.cs
- tests/MongoDB.EntityFrameworkCore.SpecificationTests/Query/NorthwindSelectQueryMongoTest.cs
> EF-76: Visiting binary and conditional expressions
